CREATE DATABASE IF NOT EXISTS authservicedb;
CREATE DATABASE IF NOT EXISTS flightservicedb; 
CREATE DATABASE IF NOT EXISTS bookingservicedb; 
USE authservicedb;
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');