pipeline {
    agent any
    stages {
        stage('Cleanup Old Image') {
            steps {
                bat 'docker rmi flight-service:latest || ver > nul'
            }
        }
        stage('Build Artifact') {
            steps {
                dir('flight-service') {
                    bat 'mvn package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('flight-service') {
                    bat 'docker build -t flight-service:latest .' 
                }
            }
        }
    }
}